/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLogin2RouteImport } from './routes/(auth)/login-2'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authInvitationExpiredRouteImport } from './routes/(auth)/invitation-expired'
import { Route as authInvitationRouteImport } from './routes/(auth)/invitation'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedSubjectsRouteRouteImport } from './routes/_authenticated/subjects/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedQuestionBankRouteRouteImport } from './routes/_authenticated/question-bank/route'
import { Route as AuthenticatedClassroomsRouteRouteImport } from './routes/_authenticated/classrooms/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedQuestionBankIndexRouteImport } from './routes/_authenticated/question-bank/index'
import { Route as AuthenticatedParentsIndexRouteImport } from './routes/_authenticated/parents/index'
import { Route as AuthenticatedModulesIndexRouteImport } from './routes/_authenticated/modules/index'
import { Route as AuthenticatedMaterialsIndexRouteImport } from './routes/_authenticated/materials/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedClassroomsIndexRouteImport } from './routes/_authenticated/classrooms/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBranchSettingsIndexRouteImport } from './routes/_authenticated/branch-settings/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedUsersRolesRouteImport } from './routes/_authenticated/users/roles'
import { Route as AuthenticatedSubjectsCurriculumsRouteImport } from './routes/_authenticated/subjects/curriculums'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings/preferences'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsInventoryRouteImport } from './routes/_authenticated/settings/inventory'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedClassroomsTemplatesRouteImport } from './routes/_authenticated/classrooms/templates'
import { Route as AuthenticatedClassroomsClassroomIdRouteRouteImport } from './routes/_authenticated/classrooms/$classroomId/route'
import { Route as AuthenticatedSuperManagementCompaniesRouteRouteImport } from './routes/_authenticated/_super-management/companies/route'
import { Route as AuthenticatedClassroomsClassroomIdIndexRouteImport } from './routes/_authenticated/classrooms/$classroomId/index'
import { Route as AuthenticatedSuperManagementCompaniesIndexRouteImport } from './routes/_authenticated/_super-management/companies/index'
import { Route as AuthenticatedQuestionBankTypeTypeRouteImport } from './routes/_authenticated/question-bank/type/$type'
import { Route as AuthenticatedClassroomsClassroomIdStudentsRouteImport } from './routes/_authenticated/classrooms/$classroomId/students'
import { Route as AuthenticatedClassroomsClassroomIdSessionsRouteImport } from './routes/_authenticated/classrooms/$classroomId/sessions'
import { Route as AuthenticatedClassroomsClassroomIdIntegrationsRouteImport } from './routes/_authenticated/classrooms/$classroomId/integrations'
import { Route as AuthenticatedSuperManagementCompaniesBranchesRouteImport } from './routes/_authenticated/_super-management/companies/branches'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authLogin2Route = authLogin2RouteImport.update({
  id: '/login-2',
  path: '/login-2',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authInvitationExpiredRoute = authInvitationExpiredRouteImport.update({
  id: '/invitation-expired',
  path: '/invitation-expired',
  getParentRoute: () => authRouteRoute,
} as any)
const authInvitationRoute = authInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsRouteRoute =
  AuthenticatedSubjectsRouteRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBankRouteRoute =
  AuthenticatedQuestionBankRouteRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassroomsRouteRoute =
  AuthenticatedClassroomsRouteRouteImport.update({
    id: '/classrooms',
    path: '/classrooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRouteRoute,
} as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSubjectsRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedQuestionBankIndexRoute =
  AuthenticatedQuestionBankIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedQuestionBankRouteRoute,
  } as any)
const AuthenticatedParentsIndexRoute =
  AuthenticatedParentsIndexRouteImport.update({
    id: '/parents/',
    path: '/parents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesIndexRoute =
  AuthenticatedModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialsIndexRoute =
  AuthenticatedMaterialsIndexRouteImport.update({
    id: '/materials/',
    path: '/materials/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassroomsIndexRoute =
  AuthenticatedClassroomsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassroomsRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchSettingsIndexRoute =
  AuthenticatedBranchSettingsIndexRouteImport.update({
    id: '/branch-settings/',
    path: '/branch-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRolesRoute = AuthenticatedUsersRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedUsersRouteRoute,
} as any)
const AuthenticatedSubjectsCurriculumsRoute =
  AuthenticatedSubjectsCurriculumsRouteImport.update({
    id: '/curriculums',
    path: '/curriculums',
    getParentRoute: () => AuthenticatedSubjectsRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsInventoryRoute =
  AuthenticatedSettingsInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedClassroomsTemplatesRoute =
  AuthenticatedClassroomsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedClassroomsRouteRoute,
  } as any)
const AuthenticatedClassroomsClassroomIdRouteRoute =
  AuthenticatedClassroomsClassroomIdRouteRouteImport.update({
    id: '/$classroomId',
    path: '/$classroomId',
    getParentRoute: () => AuthenticatedClassroomsRouteRoute,
  } as any)
const AuthenticatedSuperManagementCompaniesRouteRoute =
  AuthenticatedSuperManagementCompaniesRouteRouteImport.update({
    id: '/_super-management/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassroomsClassroomIdIndexRoute =
  AuthenticatedClassroomsClassroomIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassroomsClassroomIdRouteRoute,
  } as any)
const AuthenticatedSuperManagementCompaniesIndexRoute =
  AuthenticatedSuperManagementCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperManagementCompaniesRouteRoute,
  } as any)
const AuthenticatedQuestionBankTypeTypeRoute =
  AuthenticatedQuestionBankTypeTypeRouteImport.update({
    id: '/type/$type',
    path: '/type/$type',
    getParentRoute: () => AuthenticatedQuestionBankRouteRoute,
  } as any)
const AuthenticatedClassroomsClassroomIdStudentsRoute =
  AuthenticatedClassroomsClassroomIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedClassroomsClassroomIdRouteRoute,
  } as any)
const AuthenticatedClassroomsClassroomIdSessionsRoute =
  AuthenticatedClassroomsClassroomIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedClassroomsClassroomIdRouteRoute,
  } as any)
const AuthenticatedClassroomsClassroomIdIntegrationsRoute =
  AuthenticatedClassroomsClassroomIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedClassroomsClassroomIdRouteRoute,
  } as any)
const AuthenticatedSuperManagementCompaniesBranchesRoute =
  AuthenticatedSuperManagementCompaniesBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedSuperManagementCompaniesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/classrooms': typeof AuthenticatedClassroomsRouteRouteWithChildren
  '/question-bank': typeof AuthenticatedQuestionBankRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/subjects': typeof AuthenticatedSubjectsRouteRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/invitation': typeof authInvitationRoute
  '/invitation-expired': typeof authInvitationExpiredRoute
  '/login': typeof authLoginRoute
  '/login-2': typeof authLogin2Route
  '/otp': typeof authOtpRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/companies': typeof AuthenticatedSuperManagementCompaniesRouteRouteWithChildren
  '/classrooms/$classroomId': typeof AuthenticatedClassroomsClassroomIdRouteRouteWithChildren
  '/classrooms/templates': typeof AuthenticatedClassroomsTemplatesRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/inventory': typeof AuthenticatedSettingsInventoryRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/subjects/curriculums': typeof AuthenticatedSubjectsCurriculumsRoute
  '/users/roles': typeof AuthenticatedUsersRolesRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/branch-settings': typeof AuthenticatedBranchSettingsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/materials': typeof AuthenticatedMaterialsIndexRoute
  '/modules': typeof AuthenticatedModulesIndexRoute
  '/parents': typeof AuthenticatedParentsIndexRoute
  '/question-bank/': typeof AuthenticatedQuestionBankIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/companies/branches': typeof AuthenticatedSuperManagementCompaniesBranchesRoute
  '/classrooms/$classroomId/integrations': typeof AuthenticatedClassroomsClassroomIdIntegrationsRoute
  '/classrooms/$classroomId/sessions': typeof AuthenticatedClassroomsClassroomIdSessionsRoute
  '/classrooms/$classroomId/students': typeof AuthenticatedClassroomsClassroomIdStudentsRoute
  '/question-bank/type/$type': typeof AuthenticatedQuestionBankTypeTypeRoute
  '/companies/': typeof AuthenticatedSuperManagementCompaniesIndexRoute
  '/classrooms/$classroomId/': typeof AuthenticatedClassroomsClassroomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/invitation': typeof authInvitationRoute
  '/invitation-expired': typeof authInvitationExpiredRoute
  '/login': typeof authLoginRoute
  '/login-2': typeof authLogin2Route
  '/otp': typeof authOtpRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/classrooms/templates': typeof AuthenticatedClassroomsTemplatesRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/inventory': typeof AuthenticatedSettingsInventoryRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/subjects/curriculums': typeof AuthenticatedSubjectsCurriculumsRoute
  '/users/roles': typeof AuthenticatedUsersRolesRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/branch-settings': typeof AuthenticatedBranchSettingsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classrooms': typeof AuthenticatedClassroomsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/materials': typeof AuthenticatedMaterialsIndexRoute
  '/modules': typeof AuthenticatedModulesIndexRoute
  '/parents': typeof AuthenticatedParentsIndexRoute
  '/question-bank': typeof AuthenticatedQuestionBankIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/companies/branches': typeof AuthenticatedSuperManagementCompaniesBranchesRoute
  '/classrooms/$classroomId/integrations': typeof AuthenticatedClassroomsClassroomIdIntegrationsRoute
  '/classrooms/$classroomId/sessions': typeof AuthenticatedClassroomsClassroomIdSessionsRoute
  '/classrooms/$classroomId/students': typeof AuthenticatedClassroomsClassroomIdStudentsRoute
  '/question-bank/type/$type': typeof AuthenticatedQuestionBankTypeTypeRoute
  '/companies': typeof AuthenticatedSuperManagementCompaniesIndexRoute
  '/classrooms/$classroomId': typeof AuthenticatedClassroomsClassroomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/classrooms': typeof AuthenticatedClassroomsRouteRouteWithChildren
  '/_authenticated/question-bank': typeof AuthenticatedQuestionBankRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRouteRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/invitation': typeof authInvitationRoute
  '/(auth)/invitation-expired': typeof authInvitationExpiredRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/login-2': typeof authLogin2Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_super-management/companies': typeof AuthenticatedSuperManagementCompaniesRouteRouteWithChildren
  '/_authenticated/classrooms/$classroomId': typeof AuthenticatedClassroomsClassroomIdRouteRouteWithChildren
  '/_authenticated/classrooms/templates': typeof AuthenticatedClassroomsTemplatesRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/inventory': typeof AuthenticatedSettingsInventoryRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/subjects/curriculums': typeof AuthenticatedSubjectsCurriculumsRoute
  '/_authenticated/users/roles': typeof AuthenticatedUsersRolesRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/branch-settings/': typeof AuthenticatedBranchSettingsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/materials/': typeof AuthenticatedMaterialsIndexRoute
  '/_authenticated/modules/': typeof AuthenticatedModulesIndexRoute
  '/_authenticated/parents/': typeof AuthenticatedParentsIndexRoute
  '/_authenticated/question-bank/': typeof AuthenticatedQuestionBankIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/_super-management/companies/branches': typeof AuthenticatedSuperManagementCompaniesBranchesRoute
  '/_authenticated/classrooms/$classroomId/integrations': typeof AuthenticatedClassroomsClassroomIdIntegrationsRoute
  '/_authenticated/classrooms/$classroomId/sessions': typeof AuthenticatedClassroomsClassroomIdSessionsRoute
  '/_authenticated/classrooms/$classroomId/students': typeof AuthenticatedClassroomsClassroomIdStudentsRoute
  '/_authenticated/question-bank/type/$type': typeof AuthenticatedQuestionBankTypeTypeRoute
  '/_authenticated/_super-management/companies/': typeof AuthenticatedSuperManagementCompaniesIndexRoute
  '/_authenticated/classrooms/$classroomId/': typeof AuthenticatedClassroomsClassroomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classrooms'
    | '/question-bank'
    | '/settings'
    | '/subjects'
    | '/users'
    | '/forgot-password'
    | '/invitation'
    | '/invitation-expired'
    | '/login'
    | '/login-2'
    | '/otp'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/companies'
    | '/classrooms/$classroomId'
    | '/classrooms/templates'
    | '/settings/display'
    | '/settings/inventory'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/security'
    | '/subjects/curriculums'
    | '/users/roles'
    | '/apps'
    | '/assessments'
    | '/attendance'
    | '/branch-settings'
    | '/chats'
    | '/classrooms/'
    | '/help-center'
    | '/materials'
    | '/modules'
    | '/parents'
    | '/question-bank/'
    | '/settings/'
    | '/students'
    | '/subjects/'
    | '/tasks'
    | '/teachers'
    | '/users/'
    | '/companies/branches'
    | '/classrooms/$classroomId/integrations'
    | '/classrooms/$classroomId/sessions'
    | '/classrooms/$classroomId/students'
    | '/question-bank/type/$type'
    | '/companies/'
    | '/classrooms/$classroomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/invitation'
    | '/invitation-expired'
    | '/login'
    | '/login-2'
    | '/otp'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/classrooms/templates'
    | '/settings/display'
    | '/settings/inventory'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/security'
    | '/subjects/curriculums'
    | '/users/roles'
    | '/apps'
    | '/assessments'
    | '/attendance'
    | '/branch-settings'
    | '/chats'
    | '/classrooms'
    | '/help-center'
    | '/materials'
    | '/modules'
    | '/parents'
    | '/question-bank'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/tasks'
    | '/teachers'
    | '/users'
    | '/companies/branches'
    | '/classrooms/$classroomId/integrations'
    | '/classrooms/$classroomId/sessions'
    | '/classrooms/$classroomId/students'
    | '/question-bank/type/$type'
    | '/companies'
    | '/classrooms/$classroomId'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/_authenticated/classrooms'
    | '/_authenticated/question-bank'
    | '/_authenticated/settings'
    | '/_authenticated/subjects'
    | '/_authenticated/users'
    | '/(auth)/forgot-password'
    | '/(auth)/invitation'
    | '/(auth)/invitation-expired'
    | '/(auth)/login'
    | '/(auth)/login-2'
    | '/(auth)/otp'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/_super-management/companies'
    | '/_authenticated/classrooms/$classroomId'
    | '/_authenticated/classrooms/templates'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/inventory'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/security'
    | '/_authenticated/subjects/curriculums'
    | '/_authenticated/users/roles'
    | '/_authenticated/apps/'
    | '/_authenticated/assessments/'
    | '/_authenticated/attendance/'
    | '/_authenticated/branch-settings/'
    | '/_authenticated/chats/'
    | '/_authenticated/classrooms/'
    | '/_authenticated/help-center/'
    | '/_authenticated/materials/'
    | '/_authenticated/modules/'
    | '/_authenticated/parents/'
    | '/_authenticated/question-bank/'
    | '/_authenticated/settings/'
    | '/_authenticated/students/'
    | '/_authenticated/subjects/'
    | '/_authenticated/tasks/'
    | '/_authenticated/teachers/'
    | '/_authenticated/users/'
    | '/_authenticated/_super-management/companies/branches'
    | '/_authenticated/classrooms/$classroomId/integrations'
    | '/_authenticated/classrooms/$classroomId/sessions'
    | '/_authenticated/classrooms/$classroomId/students'
    | '/_authenticated/question-bank/type/$type'
    | '/_authenticated/_super-management/companies/'
    | '/_authenticated/classrooms/$classroomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login-2': {
      id: '/(auth)/login-2'
      path: '/login-2'
      fullPath: '/login-2'
      preLoaderRoute: typeof authLogin2RouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/invitation-expired': {
      id: '/(auth)/invitation-expired'
      path: '/invitation-expired'
      fullPath: '/invitation-expired'
      preLoaderRoute: typeof authInvitationExpiredRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/invitation': {
      id: '/(auth)/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof authInvitationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-bank': {
      id: '/_authenticated/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AuthenticatedQuestionBankRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classrooms': {
      id: '/_authenticated/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof AuthenticatedClassroomsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedSubjectsRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/question-bank/': {
      id: '/_authenticated/question-bank/'
      path: '/'
      fullPath: '/question-bank/'
      preLoaderRoute: typeof AuthenticatedQuestionBankIndexRouteImport
      parentRoute: typeof AuthenticatedQuestionBankRouteRoute
    }
    '/_authenticated/parents/': {
      id: '/_authenticated/parents/'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AuthenticatedParentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules/': {
      id: '/_authenticated/modules/'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials/': {
      id: '/_authenticated/materials/'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classrooms/': {
      id: '/_authenticated/classrooms/'
      path: '/'
      fullPath: '/classrooms/'
      preLoaderRoute: typeof AuthenticatedClassroomsIndexRouteImport
      parentRoute: typeof AuthenticatedClassroomsRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branch-settings/': {
      id: '/_authenticated/branch-settings/'
      path: '/branch-settings'
      fullPath: '/branch-settings'
      preLoaderRoute: typeof AuthenticatedBranchSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/roles': {
      id: '/_authenticated/users/roles'
      path: '/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof AuthenticatedUsersRolesRouteImport
      parentRoute: typeof AuthenticatedUsersRouteRoute
    }
    '/_authenticated/subjects/curriculums': {
      id: '/_authenticated/subjects/curriculums'
      path: '/curriculums'
      fullPath: '/subjects/curriculums'
      preLoaderRoute: typeof AuthenticatedSubjectsCurriculumsRouteImport
      parentRoute: typeof AuthenticatedSubjectsRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/inventory': {
      id: '/_authenticated/settings/inventory'
      path: '/inventory'
      fullPath: '/settings/inventory'
      preLoaderRoute: typeof AuthenticatedSettingsInventoryRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/classrooms/templates': {
      id: '/_authenticated/classrooms/templates'
      path: '/templates'
      fullPath: '/classrooms/templates'
      preLoaderRoute: typeof AuthenticatedClassroomsTemplatesRouteImport
      parentRoute: typeof AuthenticatedClassroomsRouteRoute
    }
    '/_authenticated/classrooms/$classroomId': {
      id: '/_authenticated/classrooms/$classroomId'
      path: '/$classroomId'
      fullPath: '/classrooms/$classroomId'
      preLoaderRoute: typeof AuthenticatedClassroomsClassroomIdRouteRouteImport
      parentRoute: typeof AuthenticatedClassroomsRouteRoute
    }
    '/_authenticated/_super-management/companies': {
      id: '/_authenticated/_super-management/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedSuperManagementCompaniesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classrooms/$classroomId/': {
      id: '/_authenticated/classrooms/$classroomId/'
      path: '/'
      fullPath: '/classrooms/$classroomId/'
      preLoaderRoute: typeof AuthenticatedClassroomsClassroomIdIndexRouteImport
      parentRoute: typeof AuthenticatedClassroomsClassroomIdRouteRoute
    }
    '/_authenticated/_super-management/companies/': {
      id: '/_authenticated/_super-management/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedSuperManagementCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedSuperManagementCompaniesRouteRoute
    }
    '/_authenticated/question-bank/type/$type': {
      id: '/_authenticated/question-bank/type/$type'
      path: '/type/$type'
      fullPath: '/question-bank/type/$type'
      preLoaderRoute: typeof AuthenticatedQuestionBankTypeTypeRouteImport
      parentRoute: typeof AuthenticatedQuestionBankRouteRoute
    }
    '/_authenticated/classrooms/$classroomId/students': {
      id: '/_authenticated/classrooms/$classroomId/students'
      path: '/students'
      fullPath: '/classrooms/$classroomId/students'
      preLoaderRoute: typeof AuthenticatedClassroomsClassroomIdStudentsRouteImport
      parentRoute: typeof AuthenticatedClassroomsClassroomIdRouteRoute
    }
    '/_authenticated/classrooms/$classroomId/sessions': {
      id: '/_authenticated/classrooms/$classroomId/sessions'
      path: '/sessions'
      fullPath: '/classrooms/$classroomId/sessions'
      preLoaderRoute: typeof AuthenticatedClassroomsClassroomIdSessionsRouteImport
      parentRoute: typeof AuthenticatedClassroomsClassroomIdRouteRoute
    }
    '/_authenticated/classrooms/$classroomId/integrations': {
      id: '/_authenticated/classrooms/$classroomId/integrations'
      path: '/integrations'
      fullPath: '/classrooms/$classroomId/integrations'
      preLoaderRoute: typeof AuthenticatedClassroomsClassroomIdIntegrationsRouteImport
      parentRoute: typeof AuthenticatedClassroomsClassroomIdRouteRoute
    }
    '/_authenticated/_super-management/companies/branches': {
      id: '/_authenticated/_super-management/companies/branches'
      path: '/branches'
      fullPath: '/companies/branches'
      preLoaderRoute: typeof AuthenticatedSuperManagementCompaniesBranchesRouteImport
      parentRoute: typeof AuthenticatedSuperManagementCompaniesRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authInvitationRoute: typeof authInvitationRoute
  authInvitationExpiredRoute: typeof authInvitationExpiredRoute
  authLoginRoute: typeof authLoginRoute
  authLogin2Route: typeof authLogin2Route
  authOtpRoute: typeof authOtpRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authInvitationRoute: authInvitationRoute,
  authInvitationExpiredRoute: authInvitationExpiredRoute,
  authLoginRoute: authLoginRoute,
  authLogin2Route: authLogin2Route,
  authOtpRoute: authOtpRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedClassroomsClassroomIdRouteRouteChildren {
  AuthenticatedClassroomsClassroomIdIntegrationsRoute: typeof AuthenticatedClassroomsClassroomIdIntegrationsRoute
  AuthenticatedClassroomsClassroomIdSessionsRoute: typeof AuthenticatedClassroomsClassroomIdSessionsRoute
  AuthenticatedClassroomsClassroomIdStudentsRoute: typeof AuthenticatedClassroomsClassroomIdStudentsRoute
  AuthenticatedClassroomsClassroomIdIndexRoute: typeof AuthenticatedClassroomsClassroomIdIndexRoute
}

const AuthenticatedClassroomsClassroomIdRouteRouteChildren: AuthenticatedClassroomsClassroomIdRouteRouteChildren =
  {
    AuthenticatedClassroomsClassroomIdIntegrationsRoute:
      AuthenticatedClassroomsClassroomIdIntegrationsRoute,
    AuthenticatedClassroomsClassroomIdSessionsRoute:
      AuthenticatedClassroomsClassroomIdSessionsRoute,
    AuthenticatedClassroomsClassroomIdStudentsRoute:
      AuthenticatedClassroomsClassroomIdStudentsRoute,
    AuthenticatedClassroomsClassroomIdIndexRoute:
      AuthenticatedClassroomsClassroomIdIndexRoute,
  }

const AuthenticatedClassroomsClassroomIdRouteRouteWithChildren =
  AuthenticatedClassroomsClassroomIdRouteRoute._addFileChildren(
    AuthenticatedClassroomsClassroomIdRouteRouteChildren,
  )

interface AuthenticatedClassroomsRouteRouteChildren {
  AuthenticatedClassroomsClassroomIdRouteRoute: typeof AuthenticatedClassroomsClassroomIdRouteRouteWithChildren
  AuthenticatedClassroomsTemplatesRoute: typeof AuthenticatedClassroomsTemplatesRoute
  AuthenticatedClassroomsIndexRoute: typeof AuthenticatedClassroomsIndexRoute
}

const AuthenticatedClassroomsRouteRouteChildren: AuthenticatedClassroomsRouteRouteChildren =
  {
    AuthenticatedClassroomsClassroomIdRouteRoute:
      AuthenticatedClassroomsClassroomIdRouteRouteWithChildren,
    AuthenticatedClassroomsTemplatesRoute:
      AuthenticatedClassroomsTemplatesRoute,
    AuthenticatedClassroomsIndexRoute: AuthenticatedClassroomsIndexRoute,
  }

const AuthenticatedClassroomsRouteRouteWithChildren =
  AuthenticatedClassroomsRouteRoute._addFileChildren(
    AuthenticatedClassroomsRouteRouteChildren,
  )

interface AuthenticatedQuestionBankRouteRouteChildren {
  AuthenticatedQuestionBankIndexRoute: typeof AuthenticatedQuestionBankIndexRoute
  AuthenticatedQuestionBankTypeTypeRoute: typeof AuthenticatedQuestionBankTypeTypeRoute
}

const AuthenticatedQuestionBankRouteRouteChildren: AuthenticatedQuestionBankRouteRouteChildren =
  {
    AuthenticatedQuestionBankIndexRoute: AuthenticatedQuestionBankIndexRoute,
    AuthenticatedQuestionBankTypeTypeRoute:
      AuthenticatedQuestionBankTypeTypeRoute,
  }

const AuthenticatedQuestionBankRouteRouteWithChildren =
  AuthenticatedQuestionBankRouteRoute._addFileChildren(
    AuthenticatedQuestionBankRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsInventoryRoute: typeof AuthenticatedSettingsInventoryRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsInventoryRoute: AuthenticatedSettingsInventoryRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPreferencesRoute:
      AuthenticatedSettingsPreferencesRoute,
    AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSubjectsRouteRouteChildren {
  AuthenticatedSubjectsCurriculumsRoute: typeof AuthenticatedSubjectsCurriculumsRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
}

const AuthenticatedSubjectsRouteRouteChildren: AuthenticatedSubjectsRouteRouteChildren =
  {
    AuthenticatedSubjectsCurriculumsRoute:
      AuthenticatedSubjectsCurriculumsRoute,
    AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  }

const AuthenticatedSubjectsRouteRouteWithChildren =
  AuthenticatedSubjectsRouteRoute._addFileChildren(
    AuthenticatedSubjectsRouteRouteChildren,
  )

interface AuthenticatedUsersRouteRouteChildren {
  AuthenticatedUsersRolesRoute: typeof AuthenticatedUsersRolesRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteRouteChildren: AuthenticatedUsersRouteRouteChildren =
  {
    AuthenticatedUsersRolesRoute: AuthenticatedUsersRolesRoute,
    AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  }

const AuthenticatedUsersRouteRouteWithChildren =
  AuthenticatedUsersRouteRoute._addFileChildren(
    AuthenticatedUsersRouteRouteChildren,
  )

interface AuthenticatedSuperManagementCompaniesRouteRouteChildren {
  AuthenticatedSuperManagementCompaniesBranchesRoute: typeof AuthenticatedSuperManagementCompaniesBranchesRoute
  AuthenticatedSuperManagementCompaniesIndexRoute: typeof AuthenticatedSuperManagementCompaniesIndexRoute
}

const AuthenticatedSuperManagementCompaniesRouteRouteChildren: AuthenticatedSuperManagementCompaniesRouteRouteChildren =
  {
    AuthenticatedSuperManagementCompaniesBranchesRoute:
      AuthenticatedSuperManagementCompaniesBranchesRoute,
    AuthenticatedSuperManagementCompaniesIndexRoute:
      AuthenticatedSuperManagementCompaniesIndexRoute,
  }

const AuthenticatedSuperManagementCompaniesRouteRouteWithChildren =
  AuthenticatedSuperManagementCompaniesRouteRoute._addFileChildren(
    AuthenticatedSuperManagementCompaniesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClassroomsRouteRoute: typeof AuthenticatedClassroomsRouteRouteWithChildren
  AuthenticatedQuestionBankRouteRoute: typeof AuthenticatedQuestionBankRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSubjectsRouteRoute: typeof AuthenticatedSubjectsRouteRouteWithChildren
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSuperManagementCompaniesRouteRoute: typeof AuthenticatedSuperManagementCompaniesRouteRouteWithChildren
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedBranchSettingsIndexRoute: typeof AuthenticatedBranchSettingsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMaterialsIndexRoute: typeof AuthenticatedMaterialsIndexRoute
  AuthenticatedModulesIndexRoute: typeof AuthenticatedModulesIndexRoute
  AuthenticatedParentsIndexRoute: typeof AuthenticatedParentsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClassroomsRouteRoute:
    AuthenticatedClassroomsRouteRouteWithChildren,
  AuthenticatedQuestionBankRouteRoute:
    AuthenticatedQuestionBankRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSubjectsRouteRoute: AuthenticatedSubjectsRouteRouteWithChildren,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSuperManagementCompaniesRouteRoute:
    AuthenticatedSuperManagementCompaniesRouteRouteWithChildren,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedBranchSettingsIndexRoute: AuthenticatedBranchSettingsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMaterialsIndexRoute: AuthenticatedMaterialsIndexRoute,
  AuthenticatedModulesIndexRoute: AuthenticatedModulesIndexRoute,
  AuthenticatedParentsIndexRoute: AuthenticatedParentsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
