import { MODULE_CODES } from '@edusama/common';

import { Prisma } from '../generated/prisma/client';

export const modules: Prisma.ModuleCreateManyInput[] = [
  {
    code: MODULE_CODES.branches,
    name: 'Branches',
    description: 'Branches module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.modules,
    name: 'Modules',
    description: 'Modules module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.usersAndRoles,
    name: 'Users and Roles',
    description: 'Users and roles module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.profile,
    name: 'Profile',
    description: 'Profile module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.teachers,
    name: 'Teachers',
    description: 'Teachers module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.students,
    name: 'Students',
    description: 'Students module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.parents,
    name: 'Parents',
    description: 'Parents module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.classrooms,
    name: 'Classrooms',
    description: 'Classrooms module',
    canBeDeleted: false,
    isDefault: false,
  },
  {
    code: MODULE_CODES.materials,
    name: 'Materials',
    description: 'Materials module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.assessment,
    name: 'Assessment',
    description: 'Assessment module',
    canBeDeleted: false,
    isDefault: true,
  },
  {
    code: MODULE_CODES.liveStreamSettings,
    name: 'Live Stream Settings',
    description: 'Live stream settings module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.attendance,
    name: 'Attendance',
    description: 'Attendance module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.assignments,
    name: 'Assignments',
    description: 'Assignments module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.recordedLiveClasses,
    name: 'Recorded Live Classes',
    description: 'Recorded live classes module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.certificates,
    name: 'Certificates',
    description: 'Certificates module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.accounting,
    name: 'Accounting',
    description: 'Accounting module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.paymentGateways,
    name: 'Payment Gateways',
    description: 'Payment gateways module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.payments,
    name: 'Payments',
    description: 'Payments module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.productsAndServices,
    name: 'Products and Services',
    description: 'Products and services module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.onlineStore,
    name: 'Online Store',
    description: 'Online store module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.videoCourses,
    name: 'Video Courses',
    description: 'Video courses module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.inventory,
    name: 'Inventory',
    description: 'Inventory module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.agreements,
    name: 'Agreements',
    description: 'Agreements module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.humanResources,
    name: 'Human Resources',
    description: 'Human resources module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.smartReports,
    name: 'Smart Reports',
    description: 'Smart reports module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.announcements,
    name: 'Announcements',
    description: 'Announcements module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.helpDesk,
    name: 'Help Desk',
    description: 'Help desk module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.notifications,
    name: 'Notifications',
    description: 'Notifications module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.settings,
    name: 'Settings',
    description: 'Settings module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.aiMentor,
    name: 'AI Mentor (Recommendation)',
    description: 'AI mentor (recommendation) module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.aiChat,
    name: 'AI Chat',
    description: 'AI chat module',
    canBeDeleted: false,
  },
  {
    code: MODULE_CODES.aiAutoMaterialCreation,
    name: 'AI Auto Material Creation',
    description: 'AI auto material creation module',
    canBeDeleted: false,
  },
].map((module, index) => ({
  ...module,
  id: index + 1,
}));
