
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AssignmentStatus = {
  ACTIVE: 'ACTIVE',
  RETURNED: 'RETURNED',
  PENDING_RETURN: 'PENDING_RETURN',
  LOST: 'LOST',
  DAMAGED: 'DAMAGED'
} as const

export type AssignmentStatus = (typeof AssignmentStatus)[keyof typeof AssignmentStatus]


export const AttendanceNotificationType = {
  ATTENDANCE_VIOLATION: 'ATTENDANCE_VIOLATION',
  REMINDER: 'REMINDER',
  WEEKLY_SUMMARY: 'WEEKLY_SUMMARY',
  MONTHLY_SUMMARY: 'MONTHLY_SUMMARY'
} as const

export type AttendanceNotificationType = (typeof AttendanceNotificationType)[keyof typeof AttendanceNotificationType]


export const AttendanceStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  PARTIAL: 'PARTIAL',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED'
} as const

export type AttendanceStatus = (typeof AttendanceStatus)[keyof typeof AttendanceStatus]


export const BranchStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

export type BranchStatus = (typeof BranchStatus)[keyof typeof BranchStatus]


export const ClassroomIntegrationStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  SUSPENDED: 'SUSPENDED'
} as const

export type ClassroomIntegrationStatus = (typeof ClassroomIntegrationStatus)[keyof typeof ClassroomIntegrationStatus]


export const ClassroomStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED'
} as const

export type ClassroomStatus = (typeof ClassroomStatus)[keyof typeof ClassroomStatus]


export const ClassroomTemplateStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED'
} as const

export type ClassroomTemplateStatus = (typeof ClassroomTemplateStatus)[keyof typeof ClassroomTemplateStatus]


export const CompanyStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

export type CompanyStatus = (typeof CompanyStatus)[keyof typeof CompanyStatus]


export const CurriculumStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED'
} as const

export type CurriculumStatus = (typeof CurriculumStatus)[keyof typeof CurriculumStatus]


export const DayOfWeek = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY'
} as const

export type DayOfWeek = (typeof DayOfWeek)[keyof typeof DayOfWeek]


export const DeviceCondition = {
  NEW: 'NEW',
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  FAIR: 'FAIR',
  POOR: 'POOR',
  DAMAGED: 'DAMAGED'
} as const

export type DeviceCondition = (typeof DeviceCondition)[keyof typeof DeviceCondition]


export const DeviceStatus = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  IN_REPAIR: 'IN_REPAIR',
  RETIRED: 'RETIRED',
  LOST: 'LOST',
  STOLEN: 'STOLEN'
} as const

export type DeviceStatus = (typeof DeviceStatus)[keyof typeof DeviceStatus]


export const DeviceType = {
  LAPTOP: 'LAPTOP',
  DESKTOP: 'DESKTOP',
  TABLET: 'TABLET',
  SMARTPHONE: 'SMARTPHONE',
  MONITOR: 'MONITOR',
  KEYBOARD: 'KEYBOARD',
  MOUSE: 'MOUSE',
  HEADSET: 'HEADSET',
  WEBCAM: 'WEBCAM',
  PRINTER: 'PRINTER',
  OTHER: 'OTHER'
} as const

export type DeviceType = (typeof DeviceType)[keyof typeof DeviceType]


export const EnrollmentStatus = {
  ENROLLED: 'ENROLLED',
  WITHDRAWN: 'WITHDRAWN',
  COMPLETED: 'COMPLETED'
} as const

export type EnrollmentStatus = (typeof EnrollmentStatus)[keyof typeof EnrollmentStatus]


export const Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER'
} as const

export type Gender = (typeof Gender)[keyof typeof Gender]


export const Language = {
  EN: 'EN',
  TR: 'TR',
  DE: 'DE',
  ES: 'ES',
  FR: 'FR',
  IT: 'IT',
  PT: 'PT',
  RU: 'RU',
  ZH: 'ZH',
  JA: 'JA'
} as const

export type Language = (typeof Language)[keyof typeof Language]


export const ModuleStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DELETED: 'DELETED'
} as const

export type ModuleStatus = (typeof ModuleStatus)[keyof typeof ModuleStatus]


export const RoleStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

export type RoleStatus = (typeof RoleStatus)[keyof typeof RoleStatus]


export const StudentStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  INVITED: 'INVITED',
  REQUESTED_APPROVAL: 'REQUESTED_APPROVAL',
  REQUESTED_CHANGES: 'REQUESTED_CHANGES',
  REJECTED: 'REJECTED'
} as const

export type StudentStatus = (typeof StudentStatus)[keyof typeof StudentStatus]


export const SubjectStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED'
} as const

export type SubjectStatus = (typeof SubjectStatus)[keyof typeof SubjectStatus]


export const Theme = {
  LIGHT: 'LIGHT',
  DARK: 'DARK'
} as const

export type Theme = (typeof Theme)[keyof typeof Theme]


export const TokenType = {
  RESET_PASSWORD: 'RESET_PASSWORD',
  INVITATION: 'INVITATION',
  OTP: 'OTP'
} as const

export type TokenType = (typeof TokenType)[keyof typeof TokenType]


export const UserActivity = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PREFERENCES_UPDATE: 'PREFERENCES_UPDATE',
  FAILED_LOGIN_ATTEMPT: 'FAILED_LOGIN_ATTEMPT',
  ACCOUNT_LOCKOUT: 'ACCOUNT_LOCKOUT',
  ACCOUNT_REACTIVATION: 'ACCOUNT_REACTIVATION'
} as const

export type UserActivity = (typeof UserActivity)[keyof typeof UserActivity]


export const UserStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  INVITED: 'INVITED'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const WidgetStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

export type WidgetStatus = (typeof WidgetStatus)[keyof typeof WidgetStatus]


export const LessonMaterialType = {
  DOCUMENT: 'DOCUMENT',
  AUDIO: 'AUDIO',
  VIDEO: 'VIDEO'
} as const

export type LessonMaterialType = (typeof LessonMaterialType)[keyof typeof LessonMaterialType]


export const ScheduleType = {
  FLEXIBLE: 'FLEXIBLE',
  STRICT: 'STRICT'
} as const

export type ScheduleType = (typeof ScheduleType)[keyof typeof ScheduleType]


export const ScoringType = {
  MANUAL: 'MANUAL',
  AUTOMATIC: 'AUTOMATIC'
} as const

export type ScoringType = (typeof ScoringType)[keyof typeof ScoringType]


export const QuestionType = {
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  TRUE_FALSE: 'TRUE_FALSE',
  SHORT_ANSWER: 'SHORT_ANSWER',
  MATCHING: 'MATCHING',
  FILL_IN_BLANK: 'FILL_IN_BLANK',
  ORDERING: 'ORDERING',
  ESSAY: 'ESSAY'
} as const

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType]


export const QuestionDifficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD'
} as const

export type QuestionDifficulty = (typeof QuestionDifficulty)[keyof typeof QuestionDifficulty]


export const AssessmentStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED'
} as const

export type AssessmentStatus = (typeof AssessmentStatus)[keyof typeof AssessmentStatus]


export const ClassroomIntegrationAssessmentStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED'
} as const

export type ClassroomIntegrationAssessmentStatus = (typeof ClassroomIntegrationAssessmentStatus)[keyof typeof ClassroomIntegrationAssessmentStatus]


export const StudentClassroomIntegrationStatus = {
  ELIGIBLE: 'ELIGIBLE',
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  FAILED: 'FAILED'
} as const

export type StudentClassroomIntegrationStatus = (typeof StudentClassroomIntegrationStatus)[keyof typeof StudentClassroomIntegrationStatus]


export const StudentClassroomIntegrationAssessmentSessionStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type StudentClassroomIntegrationAssessmentSessionStatus = (typeof StudentClassroomIntegrationAssessmentSessionStatus)[keyof typeof StudentClassroomIntegrationAssessmentSessionStatus]


export const SubmissionStatus = {
  SUBMITTED: 'SUBMITTED',
  AUTO_SUBMITTED: 'AUTO_SUBMITTED',
  LATE_SUBMISSION: 'LATE_SUBMISSION'
} as const

export type SubmissionStatus = (typeof SubmissionStatus)[keyof typeof SubmissionStatus]


export const AssessmentLogAction = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  RESTORED: 'RESTORED'
} as const

export type AssessmentLogAction = (typeof AssessmentLogAction)[keyof typeof AssessmentLogAction]


export const AssessmentNotificationType = {
  REMINDER: 'REMINDER',
  SUBMISSION_CONFIRMATION: 'SUBMISSION_CONFIRMATION'
} as const

export type AssessmentNotificationType = (typeof AssessmentNotificationType)[keyof typeof AssessmentNotificationType]


export const NotificationStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  FAILED: 'FAILED'
} as const

export type NotificationStatus = (typeof NotificationStatus)[keyof typeof NotificationStatus]
